import  com.codeusingjava.bootdrools.model.DepositRequest;

rule "Interest Rate for Fixed deposit duration between 1 year and 2 years and age less than 60 years"
    when
        depositObject : DepositRequest( loanType=="Fixed" && durationInYear >= 1 && durationInYear < 2 && age < 60);
    then
        depositObject.setInterestRate("5%");
end;

rule "Interest Rate for Recurring deposit duration between 1 year and 2 years and age less than 60 years"
    when
        depositObject : DepositRequest( loanType=="Recurring" && durationInYear >= 1 && durationInYear < 2 && age < 60);
    then
        depositObject.setInterestRate("3%");
end;